# Generated by Django 2.2.4 on 2019-09-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('phone_number', models.CharField(max_length=9, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('price', models.FloatField()),
                ('producer', models.ManyToManyField(to='reclamation.Producer')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='company_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.CharField(default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='post_code',
            field=models.CharField(default='none', max_length=6),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Przyjęta'), (1, 'Wysłana do producenta'), (2, 'Odpowiedź od producenta'), (3, 'Oczekiwanie na klienta'), (4, 'Zakończona')])),
                ('client', models.ManyToManyField(to='reclamation.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamation.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=16)),
                ('post_code', models.CharField(max_length=6)),
                ('phone_number', models.IntegerField(unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamation.Company')),
                ('employee', models.ManyToManyField(to='reclamation.Employee')),
            ],
        ),
    ]
