# Generated by Django 2.2.4 on 2019-09-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0002_auto_20190902_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='option_eight',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_five',
            field=models.CharField(default='test', max_length=128),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_four',
            field=models.CharField(default='test', max_length=128),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_nine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_one',
            field=models.CharField(default='test', max_length=256),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_seven',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_six',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_three',
            field=models.CharField(default='test', max_length=128),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='option_two',
            field=models.CharField(default='test', max_length=128),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reclamation.Producer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='client',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reclamation.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Przyjęta'), (1, 'Wysłana do producenta'), (2, 'Odpowiedź od producenta'), (3, 'Oczekiwanie na klienta'), (4, 'Zakończona')], default=0),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='symbol',
            field=models.CharField(default='test', max_length=32, unique=True),
        ),
    ]
