# Generated by Django 2.2.4 on 2019-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0003_auto_20190902_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='option_eight',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_five',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_four',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_nine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_one',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_seven',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_six',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_three',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_two',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='symbol',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
