# Generated by Django 2.2.4 on 2019-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0004_auto_20190902_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='option_three',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='option_two',
            field=models.DateField(),
        ),
    ]
