# Generated by Django 2.2.4 on 2019-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0005_auto_20190902_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='reclamation',
            field=models.ManyToManyField(to='reclamation.Reclamation'),
        ),
    ]
