# Generated by Django 2.2.4 on 2019-09-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0006_branch_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='reclamation',
            field=models.ManyToManyField(null=True, to='reclamation.Reclamation'),
        ),
    ]
